### PR TITLE
Added a mix integer problem of consequent size

### PR DESCRIPTION
**Pull request by bchevalier**
I wanted to add a problem that would be solved in more than 1sec by the solver to measure future improvements.

However, there is one issue. The problem take 2.2secs to be solved on my machine and, when running the command ```grunt test```, it tells me that the solving failed because it took more than 2secs.

@JWally , how to increase this time limit?

This model is an instance of the problem described in issue https://github.com/JWally/jsLPSolver/issues/38

### CODE REVIEW

**Comment by JWally** [comment]
I'll have to play around some with it and see if I can't come up with a solution.
You'll probably beat me to a solution, but it'll probably take some tinkering with how the test is set up.
It looks like there's a ```this.timeout(time)``` option in the tests (https://mochajs.org/#timeouts) that can maybe be set to infinity(?).

**Comment by bchevalier** [comment]
Thanks for the update, I do not think we should put problems that take more than 5secs to solve in the test suite triggered by a ```grunt test``` as we have to run it frequently during development. So what about a timeout of 5 secs?

**Comment by JWally** [comment]
Just pushed a commit so you can set max time in the model.expects as a "_timeout" attribute.
If its not included, 2 seconds is default. I changed the timeout on your vendor selection to 10 seconds.

**Comment by bchevalier** [comment]
cool, thanks

**Pull request merged**
