### PR TITLE
Mixed Integer Rounding cuts added

### PR DESCRIPTION
**Pull request by lvenerosy**
Changes include:
- src/MILP.js 
    Cuting process updated to include MIR cuts

- src/Model.js
    Some members moved to Tableau.js

- src/Tableau.js
    - Some members renamed
    - The bulk of the MIR cuts algorithm is in this file
        (resources used : 
        https://www.zib.de/groetschel/students/thesis_christian_raack_final_browsable.pdf
        http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.57.3720&rep=rep1&type=pdf)
    - updateConstraintCoefficient improved
    - getNewElementIndex is now in this file

- test/solver.problems.js
    The integrity check of the automated testing process has been improved to allow optimal solutions other than the one provided

It translates into improvements in the resolution time of MILP problems : 
- Monster II
    from 500ms to 70ms
- SPY_SPY_SPY_20170616
    from not finished after a few minutes to solved in 32s

### CODE REVIEW

**Comment by bchevalier** [comment]
That looks good to me.
I want to add that the modifications made to the MILP can make the solving of very small problems faster too because there is no need to go through the ```save``` and ```restore``` methods of the tableau if the MILP does a single iteration.

**Comment by bchevalier** [comment]
I want to add something else: the monster II problem is now being solved in a single iteration of the MILP B&B! (it's gonna be hard to top that)

**Comment by JWally** [comment]
I'll bump version later today and publish to NPM.
Thanks!

**Comment by bchevalier** [comment]
Thanks for the usual reactivity!

**Pull request merged**
