### PR TITLE
Fixed crash when MILP problem is unfeasible

### PR DESCRIPTION
**Pull request by bchevalier**
Done by making sure testing whether a ```bestBranch``` has been initialised. If not, the problem is unfeasible.

Also optimised the solution object returned by the MILP by making a proper class structure called ```MilpSolution```.

### CODE REVIEW

**Comment by JWally** [comment]
Merged

**Comment by bchevalier** [comment]
Yo Justin,

It actually looks like this hasn't been merged!

**Comment by JWally** [comment]
I got it. Sorry about that!

**Comment by bchevalier** [comment]
thanks!

**Comment by admin4life** [comment]
Guys thank you so much for the work you have done on this. This library is so amazing and SO FAST! Wow I was just wondering if you could push the newest version containing this merge to NPM. BIG THANKS!

**Comment by JWally** [comment]
Big thanks!
Credit goes to Brice!
I'll bump the version up tonight (CST) and push to NPM.

Thanks!
-JWW

**Comment by bchevalier** [comment]
@admin4life thanks for the feedback.
Do not hesitate to let us know of any bug you might encounter or any improvement you would like to have (more functionalities or more speed).

**Pull request merged**
